apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-dep-prod
  namespace: prod
  labels:
    app: polybot
spec:
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
        labels:
          app: polybot
    spec:
      containers:
      - name: bot-app
        image: orrmb/bot-app-prod:cicd-0.1.0
        env:
          - name: TABLE_NAME
            value: 'dev-dynamo-orb'
          - name: BUCKET_NAME
            value: 'prod-s3-orb'
        resources:
          requests:
            cpu: 300m
          limits:
            cpu: 300m
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 8443
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/ready"
            port: 8443
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: srv-polybot
  namespace: prod
spec:
  selector:
    app:  polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443


#kubectl apply -f polybot.yaml --namespace=bot-yolo-app
#orb-bot-k8s.devops-int-college.com
