apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolobot-app
  namespace: prod
  labels:
    app: yolobot-app
spec:
  selector:
    matchLabels:
      app: yolobot-app
  template:
    metadata:
        labels:
          app: yolobot-app
    spec:
      containers:
      - name: yolo-app
        image: orrmb/yolo-app-prod:cicd-0.1.1
        env:
          - name: BUCKET_NAME
            value: 'prod-s3-orb'
          - name: SQS_QUEUE_NAME
            value: 'prod-sqs-orb'
        resources:
          requests:
            cpu: 400m
          limits:
            cpu: 400m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscale-yolobot-app
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yolobot-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

  #kubectl apply -f yolobot.yaml --namespace=bot-yolo-app
