apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot-dep
  namespace: dev
  labels:
    app: polybot
spec:
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
        labels:
          app: polybot
    spec:
      containers:
      - name: bot-app
        image: orrmb/bot-app-dev:cicd-0.0.9
        env:
          - name: TABLE_NAME
            value: 'dev-dynamo-orb'
          - name: BUCKET_NAME
            value: 'dev-s3-orb'
        resources:
          requests:
            cpu: 300m
          limits:
            cpu: 300m
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 443
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/ready"
            port: 443
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: srv-polybot
  namespace: dev
spec:
  selector:
    app:  polybot
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
